# Generated by Django 4.0.4 on 2022-04-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(choices=[('itching', 'itching'), ('skin rash', 'skin rash'), ('nodal skin eruptions', 'nodal skin eruptions'), ('continuous sneezing', 'continuous sneezing'), ('shivering', 'shivering'), ('chills', 'chills'), ('joint pain', 'joint pain'), ('stomach pain', 'stomach pain'), ('acidity', 'acidity'), ('ulcers on tongue', 'ulcers on tongue'), ('muscle wasting', 'muscle wasting'), ('vomiting', 'vomiting'), ('burning micturition', 'burning micturition'), ('spotting urination', 'spotting urination'), ('fatigue', 'fatigue'), ('weight gain', 'weight gain'), ('anxiety', 'anxiety'), ('cold hands and feets', 'cold hands and feets'), ('mood swings', 'mood swings'), ('weight loss', 'weight loss'), ('restlessness', 'restlessness'), ('lethargy', 'lethargy'), ('patches in throat', 'patches in throat'), ('irregular sugar level', 'irregular sugar level'), ('cough', 'cough')], max_length=255)),
            ],
        ),
    ]
